using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Discord.Commands;
using Discord.WebSocket;

namespace SavageBot.Modules
{
    [Group("werd")]
    [Summary("A game where you try to guess a five letter word generated by the bot.")]
    public class Werd : ModuleBase<SocketCommandContext>
    {
        [Summary("Start a game.")]
        public class Start : ModuleBase<SocketCommandContext>
        {

        }

        [Summary("Guess a word.")]
        public class Guess : ModuleBase<SocketCommandContext>
        {

        }

        [Summary("End the current game.")]
        [RequireUserPermission(Discord.GuildPermission.Administrator)] // only admins can end a game prematurely unless a vote is passed
        public class End : ModuleBase<SocketCommandContext>
        {

        }

        [Summary("Vote to end the game.")]
        public class Vote : ModuleBase<SocketCommandContext>
        {

        }
    }
}
